#!/bin/bash

if [ 1 != $# ]; then
    echo "Please specify the file to run"
    exit 1
fi

fname="$1"
# name of the executable (assumes file ends with ".rs")
exe_name="${fname:0:${#fname}-3}"
# compile program
rustc "$fname" -o "$exe_name"
# run the program
"$exe_name"
# remove the executable
rm "$exe_name"
