#!/bin/bash

FOUT=""
MAIN=1

main() {

    trap "exit_via_signal" EXIT

    # rust version info
    rustc -V

    # each iteration runs a new rust program
    while true; do
        set_fout
        echo -n "" > "$FOUT"
        build_rust_prog
    done
}

set_fout() {
    FOUT="$(mktemp tmpXXXXXXXXXX.rs)"
}

build_rust_prog() {

    # start the main function
    if [ 1 == "$MAIN" ]; then
        echo -e ">>> fn main() {"
        echo -e " fn main() {" >> "$FOUT"
    fi

    # detect first iteration
    first=1

    # get user input
    while true; do

        # first line only - add leading whitespace
        if [ 1 == "$MAIN" ] && [ 1 == "$first" ]; then
            read -p "...     " line
        else
            read -p "... " line
        fi

        # run the program
        if [[ -z "$line" ]]; then
            ./rustrun "$FOUT"
            return
        # start over
        elif [[ "!new" == "$line" ]]; then
            remove_temp_file
            return
        # exit the script
        elif [[ "!exit" == "$line" ]]; then
            exit_via_console
        # append code to the program
        else
            # first line only - add padding
            if [ 1 == "$MAIN" ] && [ 1 == "$first" ]; then
                line="    $line"
                first=0
            fi
            echo "$line" >> "$FOUT"
        fi
    done
}

# if exiting via the "!exit" command
exit_via_console() {
    exit_actions
    exit
}

# if exiting via CTRL+'c'
exit_via_signal() {
    exit_actions
}

exit_actions() {
    remove_temp_file
}

remove_temp_file() {
    if [ -f "$FOUT" ]; then
        rm "$FOUT"
    fi
}

main
